# Skywire Wing Commander example configuration file
[telegram]
apikey = "YOUR-BOT-API-KEY-HERE"
chatid = YOUR-PRIVATE-BOT-CHATID-HERE(AS AN INTEGER)
admin = "YOUR TELEGRAM USERID HERE"
debug = false

[monitor]
intervalsec = 10
heartbeatintmin = 120

[skymanager]
address="127.0.0.1:8000"