# Skywire Wing Commander configuration file
[telegram]
apikey = "575938715:AAFA2DLeRe-4iULHYIJvvDUE602pp7_pi8U"
chatid = 501290519
admin = "@BigOokie"
debug = false

[monitor]
intervalsec = 2
heartbeatintmin = 1

[skymanager]
address="127.0.0.1:8000"