# Skywire Wing Commander example configuration file
[telegram]
apikey = "YOUR-BOT-API-KEY-HERE"
chatid = "YOUR-PRIVATE-BOT-CHATID-HERE"
admin = "YOUR TELEGRAM USERID HERE"
debug = false

[monitor]
intervalsec = 2
heatbeatintmin = 60

[skymanager]
address="127.0.0.1:8000"